--Creating Tables
--Run entire script
CREATE TABLE careplans (
Id VARCHAR(100)
,START TIMESTAMP
,STOP TIMESTAMP
,PATIENT VARCHAR(100)
,ENCOUNTER VARCHAR(100)
,CODE int
,DESCRIPTION VARCHAR(500)
,REASONCODE VARCHAR(100)
,REASONDESCRIPTION VARCHAR(100)
);

CREATE TABLE conditions (
START DATE
,STOP DATE
,PATIENT VARCHAR(1000)
,ENCOUNTER VARCHAR(1000)
,CODE VARCHAR(1000)
,DESCRIPTION VARCHAR(200)
);

CREATE TABLE encounters (
 Id VARCHAR(100)
,START TIMESTAMP
,STOP TIMESTAMP
,PATIENT VARCHAR(100)
,ORGANIZATION VARCHAR(100)
,PROVIDER VARCHAR(100)
,PAYER VARCHAR(100)
,ENCOUNTERCLASS VARCHAR(100)
,CODE VARCHAR(100)
,DESCRIPTION VARCHAR(100)
,BASE_ENCOUNTER_COST float
,TOTAL_CLAIM_COST float
,PAYER_COVERAGE float
,REASONCODE VARCHAR(100)
,REASONDESCRIPTION VARCHAR(100)
);

CREATE TABLE immunizations
(
 DATE TIMESTAMP
,PATIENT VARCHAR(100)
,ENCOUNTER VARCHAR(100)
,CODE int
,DESCRIPTION VARCHAR(500)
,BASE_COST float
);

CREATE TABLE observations (
DATE TIMESTAMP
,PATIENT VARCHAR(100)
,ENCOUNTER VARCHAR (100)
,CATEGORY VARCHAR (100)
,CODE VARCHAR(100)
,DESCRIPTION VARCHAR (1000)
,VALUE VARCHAR (1000)
,UNITS VARCHAR (100)
,TYPE VARCHAR (100)
);

CREATE TABLE organizations (
Id VARCHAR(100)
,NAME VARCHAR(100)
,ADDRESS VARCHAR(100)
,CITY VARCHAR(100)
,STATE VARCHAR(100)
,ZIP int
,LAT float
,LON float
,PHONE VARCHAR(100)
,REVENUE float
,UTILIZATION int
);

CREATE TABLE patients
(
 Id VARCHAR(100)
,BIRTHDATE date
,DEATHDATE date
,SSN VARCHAR(100)
,DRIVERS VARCHAR(100)
,PASSPORT VARCHAR(100)
,PREFIX VARCHAR(100)
,FIRST VARCHAR(100)
,LAST VARCHAR(100)
,SUFFIX VARCHAR(100)
,MAIDEN VARCHAR(100)
,MARITAL VARCHAR(100)
,RACE VARCHAR(100)
,ETHNICITY VARCHAR(100)
,GENDER VARCHAR(100)
,BIRTHPLACE VARCHAR(100)
,ADDRESS VARCHAR(100)
,CITY VARCHAR(100)
,STATE VARCHAR(100)
,COUNTY VARCHAR(100)
,FIPS int 
,ZIP int
,LAT float
,LON float
,HEALTHCARE_EXPENSES float
,HEALTHCARE_COVERAGE float
,INCOME int
);

CREATE TABLE providers (
Id VARCHAR(100)
,ORGANIZATION VARCHAR(100)
,NAME VARCHAR(100)
,GENDER VARCHAR(100)
,SPECIALITY VARCHAR(100)
,ADDRESS VARCHAR(100)
,CITY VARCHAR(100)
,STATE VARCHAR(100)
,ZIP int
,LAT float
,LON float
,ENCOUNTERS int
,PROCEDURES int
);

CREATE TABLE procedures (
START TIMESTAMP
,STOP TIMESTAMP
,PATIENT VARCHAR(100)
,ENCOUNTER VARCHAR(100)
,CODE VARCHAR(100)
,DESCRIPTION VARCHAR(500)
,BASE_COST float
,REASONCODE VARCHAR(100)
,REASONDESCRIPTION VARCHAR(100)
);

CREATE TABLE medications (
START DATE
,STOP DATE
,PATIENT VARCHAR(100)
,PAYER VARCHAR(100)
,ENCOUNTER VARCHAR(1000)
,CODE VARCHAR(1000)
,DESCRIPTION VARCHAR(200)	
,BASE_COST float
,PAYER_COVERAGE float
,DISPENSES int	
,TOTALCOST float
,REASONCODE VARCHAR(100)
,REASONDESCRIPTION VARCHAR(100)
);